#!/bin/bash

peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["1","zhangjiang","2019/3/9/1","50"]}'
peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["2","zhangjiang","2019/3/9/1","50"]}'
peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["3","zhangjiang","2019/3/9/1","50"]}'
peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["4","zhangjiang","2019/3/9/1","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["5","zhangjiang","2019/3/9/1","40"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["6","zhangjiang","2019/3/9/1","40"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["7","zhangjiang","2019/3/9/1","40"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["8","zhangjiang","2019/3/9/1","40"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["9","yangpu","2019/3/9/1","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["10","yangpu","2019/3/9/1","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["11","yangpu","2019/3/9/1","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["12","yangpu","2019/3/9/1","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["13","yangpu","2019/3/9/1","30"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["14","yangpu","2019/3/9/1","30"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["15","yangpu","2019/3/9/1","30"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["16","yangpu","2019/3/9/1","30"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["17","zhangjiang","2019/3/9/2","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["18","zhangjiang","2019/3/9/2","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["19","zhangjiang","2019/3/9/2","50"]}'
#peer chaincode invoke -o orderer.example.com:7050 -C mychannel -n group_activity -c '{"function":"createRequest","Args":["20","zhangjiang","2019/3/9/2","50"]}'
